### ISSUE TITLE
UTF-8 bug when two month

### ISSUE THREAD

**Issue by rshadow** [copycat-killer/lain#171] opened 2016-02-27 13:16 UTC
Reproduce:
1. Use calendar with additional parameters:

lain.widgets.calendar:attach(widgetdate, {
    font = "Monospace", position = "top_right", post_cal = "-A1"
})

2. On mouse click `widgetdate` show previous months. Current date shifted, but steel showed in second month.
3. Current date "highlighted" with unknown utf8 symbols.

**Comment by rshadow** [comment] 2016-02-27 13:48
![2016-02-27 16 47 57](https://cloud.githubusercontent.com/assets/737152/13373204/e38d2e0c-dd71-11e5-9682-ebd46faffd01.png)

**Comment by copycat-killer** [comment] 2016-02-27 18:31
Duplicate of #170

**Closed by copycat-killer** 2016-02-27 18:31 UTC
Labels: duplicate
