### ISSUE TITLE
Write a month under the current date.

### ISSUE THREAD

**Issue by rshadow** [copycat-killer/lain#172] opened 2016-02-27 13:20 UTC
When i use two months in calendar like:
```
lain.widgets.calendar:attach(widgetdate, {
    font = "Monospace", position = "top_right", post_cal = "-A1"
})
```
then it is not obvious what the big current date of the month belongs.

Please add configuration parameter to show current month inder big current date.

**Comment by aajjbb** [comment] 2016-02-27 13:34
What's the goal of this `post_cal = "-A1"` in there ? Trying to use it broke my system.

Do you have a screenshot of the situation ?

**Comment by rshadow** [comment] 2016-02-27 13:44
```
$ LANG=C cal
   February 2016      
Su Mo Tu We Th Fr Sa  
    1  2  3  4  5  6  
 7  8  9 10 11 12 13  
14 15 16 17 18 19 20  
21 22 23 24 25 26 27  
28 29
```

```
$ LANG=C cal -A1
   February 2016           March 2016       
Su Mo Tu We Th Fr Sa  Su Mo Tu We Th Fr Sa  
    1  2  3  4  5  6         1  2  3  4  5  
 7  8  9 10 11 12 13   6  7  8  9 10 11 12  
14 15 16 17 18 19 20  13 14 15 16 17 18 19  
21 22 23 24 25 26 27  20 21 22 23 24 25 26  
28 29                 27 28 29 30 31
```

**Comment by rshadow** [comment] 2016-02-27 13:46
![2016-02-27 16 44 54](https://cloud.githubusercontent.com/assets/737152/13373192/9b2cd680-dd71-11e5-9f6a-607d7e303081.png)

**Comment by copycat-killer** [comment] 2016-02-27 18:30
Duplicate of #170

**Closed by copycat-killer** 2016-02-27 18:30 UTC
Labels: duplicate
