### ISSUE TITLE
Redshift toggle widget text not changing

### ISSUE THREAD

**Issue by jnor** [copycat-killer/lain#301] opened 2017-02-01 08:27 UTC
Hello,

The Redshift widget work, however when I toggle the program the text "RS off" and "RS on" does not change. I have used the examples provided by the documentation.

Regards
JN

**Comment by copycat-killer** [comment] 2017-02-01 11:31
Are you toggling by not clicking on the widget itself?

**Comment by jnor** [comment] 2017-02-01 12:51
The text also does not change from Off when I toggle by clicking widget itself, same when I use key. I'm using multicolor theme.
$ awesome -v
awesome v4.0-170-g6c248485

running latest master branch of lain

**Comment by copycat-killer** [comment] 2017-02-01 17:36
Can you paste your `rc.lua`?

**Comment by copycat-killer** [comment] 2017-02-07 08:22
@jnor Also, it'd be useful to have some `stderr`. 

If you use `startx` to start Awesome, you can fetch it in `~/.xorg.log` with

```lua
startx -- -keeptty -nolisten tcp > $HOME/.xorg.log 2>&1
```

**Comment by copycat-killer** [comment] 2017-02-24 12:52
@jnor Pinging you. Please, read my previous posts.

**Comment by copycat-killer** [comment] 2017-03-01 12:05
The widget is confirmed working, the point was some misconfiguration, or some specific case on your machine.

Since you don't seem to care, I'm closing this.

If you have any update or wiki enhancement suggestion, feel free to reply.

**Closed by copycat-killer** 2017-03-01 12:05 UTC
